{% set name = "libpsl" %}
{% set version = "0.21.5" %}

package:
  name: libpsl-split
  version: head

source:
  url: https://github.com/rockdaboot/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1dcc9ceae8b128f3c0b3f654decd0e1e891afc6ff81098f227ef260449dae208
  patches:
    - icu-win.patch

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - m2-patch
    - meson
    - pkgconf-tools

outputs:
  - name: libpsl-runtime
    files:
      - Library/bin/*.dll
  - name: libpsl-dev
    files:
      - Library/include
      - Library/lib
      - Library/share
    build:
      run_exports:
        - {{ pin_subpackage('libpsl-runtime', max_pin='x') }}
  - name: libpsl-tools
    files:
      - Library/bin/*.exe
    requirements:
      - libpsl-runtime

about:
  home: https://github.com/rockdaboot/libpsl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A C library to handle the Public Suffix List
