context:
  version: "0.23.0"

recipe:
  name: libpsl-split
  version: ${{ version }}

source:
  url: https://github.com/rockdaboot/libpsl/releases/download/${{ version }}/libpsl-${{ version }}.tar.gz
  sha256: f39b9631b3d369a21259ea4654f8875c0ec6995ce9551c0eb5d423e4c011f911

outputs:
  - staging:
      name: libpsl-split
    requirements:
      build:
        - vs
        - ninja
        - meson
        - pkgconf-tools

  - package:
      name: libpsl-runtime
    inherit: libpsl-split
    build:
      files:
        include:
          - Library/bin/*.dll
  - package:
      name: libpsl-dev
    inherit: libpsl-split
    build:
      files:
        include:
          - Library/include
          - Library/lib
          - Library/share
    requirements:
      run:
        - libpsl-runtime
      run_exports:
        - libpsl-runtime
  - package:
      name: libpsl-tools
    inherit: libpsl-split
    build:
      files:
        include:
          - Library/bin/*.exe
          - Library/bin/psl-make-dafsa
    requirements:
      run:
        - libpsl-runtime

  - package:
      name: libpsl-full
    requirements:
      run:
        - libpsl-tools
        - libpsl-dev

about:
  license: MIT
  license_file: LICENSE
  summary: A C library to handle the Public Suffix List
  homepage: https://github.com/rockdaboot/libpsl

