{% set version = "0.26" %}

package:
  name: gettext
  version: {{ version }}

source:
  url: https://ftp.gnu.org/pub/gnu/gettext/gettext-{{ version }}.tar.xz
  sha256: d1fb86e260cfe7da6031f94d2e44c0da55903dbae0a2fa0fae78c91ae1b56f00

requirements:
  build:
    - {{ compiler('c') }}
    - m2-aux
    - m2-autoconf
    - m2-automake-wrapper
    - m2-bash
    - m2-findutils
    - m2-grep
    - m2-libtool
    - m2-m4
    - m2-make
    - m2-patch

