{% set version = "8.15.0" %}

package:
  name: curl-split
  version: {{ version }}

source:
  url: http://curl.haxx.se/download/curl-{{ version }}.tar.xz
  sha256: 6cd0a8a5b126ddfda61c94dc2c3fc53481ba7a35461cf7c5ab66aa9d6775b609
  patches:
    - cert.patch

requirements:
  build:
    - {{ compiler('c') }}
    - cmake-no-system  # [win]
    - pkgconf-tools
    - c-ares-dev
    - libpsl-dev
    - nghttp3-dev
    - zlib-dev
    - zstd-dev
    - libssh-dev
    - openssl-dev
    - prefix-stub-runtime
    - prefix-stub-dev

outputs:
  - name: curl-runtime
    files:
      - Library/bin/*.dll
    requirements:
      - c-ares-runtime
      - libpsl-runtime
      - nghttp3-runtime
      - openssl-runtime
      - libssh-runtime
      - zlib-runtime
      - zstd-runtime
  - name: curl-dev
    build:
      run_exports:
        strong:
          - {{ pin_subpackage('curl-runtime', max_pin='x') }}
    files:
      - Library/include
      - Library/lib
      - Library/share
  - name: curl-tools
    files:
      - Library/bin/*.exe
      - Library/bin/curl-config
    requirements:
      - curl-runtime

about:
  home: http://curl.haxx.se/
  license: curl
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax

  description: |
    Curl is an open source command line tool and library for transferring data
    with URL syntax. It is used in command lines or scripts to transfer data.
  doc_url: https://curl.haxx.se/docs/
  dev_url: https://github.com/curl/curl
  doc_source_url: https://github.com/curl/curl/tree/master/docs

extra:
  recipe-maintainers:
    - msarahan
    - jakirkham
    - ocefpaf
    - mingwandroid
    - xylar