context:
  version: "3.0.6"

recipe:
  name: pkgconf-split
  version: ${{ version }}

source:
  url: https://github.com/pkgconf/pkgconf/releases/download/pkgconf-${{ version }}/pkgconf-${{ version }}.tar.xz
  sha256: c88a653fbabfa2a5857a30f6b6ad6c40dbacc3b7c72cc066e5c7dc4571cbddaa

outputs:
  - staging:
      name: pkgconf-split
    requirements:
      build:
        - vs
        - meson
        - ninja

  - package:
      name: pkgconf-runtime
    inherit:
      from: pkgconf-split
    build:
      files:
        include:
          - Library/bin/*.dll
  - package:
      name: pkgconf-dev
    inherit:
      from: pkgconf-split
    build:
      files:
        include:
          - Library
        exclude:
          - Library/bin
    requirements:
      run:
        - pkgconf-runtime
      run_exports:
        - pkgconf-runtime
  - package:
      name: pkgconf-tools
    inherit:
      from: pkgconf-split
    build:
      files:
        - Library/bin/*.exe
    requirements:
      run:
        - pkgconf-runtime
  - package:
      name: pkgconf-full
    requirements:
      run:
        - pkgconf-dev
        - pkgconf-tools

about:
  license: MIT
  license_file: COPYING
  summary: package compiler and linker metadata toolkit
  homepage: https://github.com/pkgconf/pkgconf
  repository: https://github.com/pkgconf/pkgconf

