context:
  version: "78.2"

recipe:
  name: icu4c
  version: ${{ version }}

source:
  url: https://github.com/unicode-org/icu/releases/download/release-${{ version }}/icu4c-${{ version }}-sources.zip
  sha256: af38c3d4904e47e1bc2dd7587922ee2aec312fefa677804582e3fecca3edb272
  patches:
    - config.patch

outputs:
  - staging:
      name: icu4c-split
    requirements:
      build:
        - vs
        - m2-aux
        - m2-autoconf
        - m2-automake-wrapper
        - m2-bash
        - m2-findutils
        - m2-grep
        - m2-libtool
        - m2-m4
        - m2-make
        - python
    build:
      script: bld.ps1

  - package:
      name: icu4c-runtime
    inherit: icu4c-split
    build:
      files:
        include:
          - Library/bin/*.dll
  - package:
      name: icu4c-dev
    inherit: icu4c-split
    build:
      files:
        include:
          - Library/include
          - Library/lib
          - Library/share
    requirements:
      run:
        - icu4c-runtime
      run_exports:
        - icu4c-runtime
  - package:
      name: icu4c-tools
    inherit: icu4c-split
    build:
      files:
        include:
          - Library/bin/*.exe
    requirements:
      run:
        - icu4c-runtime

about:
  license: Unicode-3.0
  summary: International Components for Unicode
  homepage: https://icu.unicode.org/
  repository: https://github.com/unicode-org/icu
