context:
  version: "1.0"

recipe:
  name: gettext
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/pub/gnu/gettext/gettext-${{ version }}.tar.xz
  sha256: 71132a3fb71e68245b8f2ac4e9e97137d3e5c02f415636eb508ae607bc01add7

outputs:
  - staging:
      name: gettext-split
    requirements:
      build:
        - vs
        - m2-aux
        - m2-autoconf
        - m2-automake-wrapper
        - m2-bash
        - m2-findutils
        - m2-grep
        - m2-libtool
        - m2-m4
        - m2-make
        - m2-patch
      host:
        - libxml2-dev
        - libiconv-dev
        - libunistring-dev
    build:
      script: bld.ps1

  - package:
      name: libintl-runtime
    inherit:
      from: gettext-split
    build:
      files:
        - Library/bin/intl-*.dll
    requirements:
      run:
        - libiconv-runtime
  - package:
      name: libintl-dev
    inherit:
      from: gettext-split
    build:
      files:
        include:
          - Library/include/libintl.h
          - Library/lib/intl.lib
          - Library/share/man/man3
    requirements:
      run:
        - libintl-runtime
      run_exports:
        - libintl-runtime

  - package:
      name: libasprintf-runtime
    inherit:
      from: gettext-split
    build:
      files:
        - Library/bin/asprintf-*.dll
  - package:
      name: libasprintf-dev
    inherit:
      from: gettext-split
    build:
      files:
        - Library/lib/asprintf.lib
        - Library/include/autosprintf.h
        - Library/share/info/autosprintf.info
        - Library/share/doc/libasprintf

  - package:
      name: libtextstyle-dev
    inherit:
      from: gettext-split
    build:
      files:
        include:
          - Library/include/textstyle
          - Library/include/textstyle.h
          - Library/lib/textstyle.lib
          - Library/share/doc/libtextstyle
          - Library/share/info/libtextstyle.info
    requirements:
      run:
        - libtextstyle-runtime
      run_exports:
        - libtextstyle-runtime
  - package:
      name: libtextstyle-runtime
    inherit:
      from: gettext-split
    build:
      files:
        include:
          - Library/bin/textstyle-*.dll
    requirements:
      run:
        - libiconv-runtime
  - package:
      name: libtextstyle
    requirements:
      run:
        - libtextstyle-dev
        - libtextstyle-runtime
  - package:
      name: gettext-dev
    inherit:
      from: gettext-split
    build:
      files:
        include:
          - Library/include/gettext-po.h
          - Library/lib/gettext*.lib
          - Library/share
        exclude:
          - Library/share/doc/lib*
          - Library/share/man/man3
          - Library/share/info/libtextstyle.info
          - Library/share/info/autosprintf.info
          - Library/share/locale
    requirements:
      run:
        - gettext-runtime
        - libintl-dev
        - libiconv-dev
        - libtextstyle-dev
        - libunistring-dev
        - libxml2-dev
      run_exports:
        - gettext-runtime
  - package:
      name: gettext-runtime
    inherit:
      from: gettext-split
    build:
      files:
        include:
          - Library/bin/gettext*.dll
    requirements:
      run:
        - libiconv-runtime
        - libintl-runtime
        - libtextstyle-runtime
        - libunistring-runtime
        - libxml2-runtime
  - package:
      name: gettext-tools
    inherit:
      from: gettext-split
    build:
      files:
        include:
          - Library/bin/*.exe
          - Library/bin/*.sh
          - Library/bin/autopoint
          - Library/bin/gettextize
          - Library/libexec
          - Library/share/locale
    requirements:
      run:
        - gettext-runtime
  - package:
      name: gettext
    requirements:
      run:
        - gettext-dev
        - gettext-runtime
        - gettext-tools

about:
  license: LGPL-2.1-or-later AND GPL-3.0-or-later
  summary: Internationalization package
  homepage: https://www.gnu.org/software/gettext/

