context:
  name: bzip2
  version: "1.0.9"

recipe:
  name: ${{ name }}
  version: ${{ version }}

cache:
  source:
    url: https://gitlab.com/paperchalice/bzip2/-/archive/master/bzip2-master.zip
  requirements:
    build:
      - cmake-no-system
      - visual-studio
  build:
    script: bld.ps1

outputs:
  - package:
      name: bzip2-dev
    build:
      files:
        - Library/lib
        - Library/include
        - Library/share/man
    requirements:
      run_exports:
          - bzip2-runtime
      run:
        - bzip2-runtime
  - package:
      name: bzip2-runtime
    build:
      files:
        - Library/bin/*.dll
  - package:
      name: bzip2-tools
    requirements:
      run:
        - bzip2-runtime
    build:
      files:
        - Library/bin/*.exe

about:
  home: https://gitlab.com/bzip2/bzip2
  license_family: BSD
  license_file: LICENSE
  license: bzip2-1.0.6
  summary: high-quality data compressor
  description: |
    Bzip2 is a freely available high-quality data compressor. It typically
    compresses files to within 10% to 15% of the best available techniques,
    whilst being around twice as fast at compression and six times faster
    at decompression.
  dev_url: https://gitlab.com/bzip2/bzip2
