{% set version = "1.1.0" %}

package:
  name: brotli-split
  version: head

source:
  fn: brotli-{{ version }}.tar.gz
  url: https://github.com/google/brotli/archive/v{{ version }}.tar.gz
  sha256: e720a6ca29428b803f4ad165371771f5398faba397edf6778837a18599ea13ff


requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

outputs:
  - name: brotli-runtime
    files:
      - Library/bin/*.dll
  - name: brotli-dev
    files:
      - Library/include
      - Library/lib
    build:
      run_exports:
        - brotli-runtime
  - name: brotli-tools
    files:
      - Library/bin/*.exe
    requirements:
      - brotli-runtime
  - name: brotli-full
    requirements:
      - brotli-tools
      - brotli-runtime
      - brotli-dev
