{% set version = "1.4.1" %}

package:
  name: libunistring
  version: head

source:
  url: https://ftp.gnu.org/gnu/libunistring/libunistring-{{ version }}.tar.xz
  sha256: 67d88430892527861903788868c77802a217b0959990f7449f2976126a307763

requirements:
  build:
    - {{ compiler('c') }}
    - m2-aux
    - m2-autoconf
    - m2-automake-wrapper
    - m2-bash
    - m2-findutils
    - m2-grep
    - m2-libtool
    - m2-m4
    - m2-make
    - m2-patch
  host:
    - libiconv-dev
    - libiconv-runtime
  run:
    - libunistring-runtime
    - libunistring-dev

outputs:
  - name: libunistring-runtime
    files:
      include:
        - Library/bin/*.dll
    requirements:
      run:
        - libiconv-runtime
  - name: libunistring-dev
    files:
      include:
        - Library/include
        - Library/lib
        - Library/share
    requirements:
      run:
        - libunistring-runtime
      run_exports:
        - libunistring-runtime
