{% set version = "3.5.0" %}

package:
  name: openssl-split
  version: {{ version }}

source:
  url: https://github.com/openssl/openssl/releases/download/openssl-{{ version }}/openssl-{{ version }}.tar.gz
  sha256: 344d0a79f1a9b08029b0744e2cc401a43f9c90acd1044d09a530b4885a8e9fc0
  patches:
    - lib.patch
    - reloc.patch

requirements:
  build:
    - {{ compiler('c') }}
    - nasm
    - perl
    - m2-patch
    - zlib
    - brotli-full
    - zstd-dev
    - prefix-stub-dev
  # Empty host section to ensure that this is identified as cb3
  host:

outputs:
  - name: openssl-runtime
    files:
      - Library/bin/*.dll
      - Library/SSL
      - Library/lib/engines-3
      - Library/lib/ossl-modules
    requirements:
      - brotli-runtime
      - prefix-stub-runtime
      - zlib-runtime
      - zstd-runtime
  - name: openssl-dev
    files:
      - Library/lib
      - Library/include
      - Library/html
    build:
      run_exports:
          - openssl-runtime
    requirements:
      - brotli-dev
      - zlib-dev
      - zstd-dev
  - name: openssl-tools
    files:
      - Library/bin/*.exe
      - Library/bin/*.pl
    requirements:
      - openssl-runtime
  - name: openssl-full
    requirements:
      - openssl-tools
      - openssl-dev
