{% set version = "1.18" %}

package:
  name: libiconv
  version: {{ version }}

source:
  url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-{{ version }}.tar.gz
  sha256: 3b08f5f4f9b4eb82f151a7040bfd6fe6c6fb922efe4b1659c66ea933276965e8

requirements:
  build:
    - {{ compiler('c') }}
    - gettext-tools
    - m2-aux
    - m2-autoconf
    - m2-automake-wrapper
    - m2-bash
    - m2-grep
    - m2-libtool
    - m2-m4
    - m2-make
    - m2-patch
  run:
    - libiconv-dev
    - libiconv-runtime
    - libcharset-dev
    - libcharset-runtime
    - libiconv-tools

outputs:
  - name: libiconv-runtime
    include:
      files:
        - Library/bin/iconv-2.dll
  - name: libiconv-dev
    include:
      files:
        - Library/include/iconv.h
        - Library/lib/iconv.lib
        - Library/share/doc
        - Library/share/man
    requirements:
      run:
        - libiconv-runtime
      run_exports:
        - libiconv-runtime
  - name: libcharset-runtime
    files:
      - Library/bin/charset-1.dll
  - name: libcharset-dev
    include:
      files:
        - Library/include/libcharset.h
        - Library/include/localcharset.h
        - Library/lib/charset.lib
    requirements:
      run:
        - libcharset-runtime
      run_exports:
        - libcharset-runtime
  - name: libiconv-tools
    requirements:
      - libiconv-runtime
      - libintl-runtime
    files:
      include:
        - Library/bin/*.exe
        - Library/share/locale

about:
  home: https://www.gnu.org/software/libiconv/
  license: GPL-3.0-only AND LGPL-2.1-only
  license_file:
    - COPYING
    - COPYING.LIB
  summary: Split feedstock providing iconv and libiconv for systems which don't have one (or that cannot convert from/to Unicode.)
