{% set version = "2.15.1" %}

package:
  name: libxml2
  version: head

source:
  url: https://gitlab.gnome.org/GNOME/libxml2/-/archive/v{{ version }}/libxml2-v{{ version }}.tar.gz
  sha256: 0a5ebf8fa131585748d661ae692503483aff39d9b29b6c4b342cd80d422f246c

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - libiconv-dev
    - zlib-dev
  run:
    - libxml2-runtime
    - libxml2-dev
    - libxml2-tools

outputs:
  - name: libxml2-runtime
    files:
      include:
        - Library/bin/*.dll
    requirements:
      run:
        - libiconv-runtime
        - zlib-runtime
  - name: libxml2-dev
    files:
      include:
        - Library/include
        - Library/lib
        - Library/share
    run_exports:
      - libxml2-runtime
    requirements:
      - libiconv-dev
      - zlib-dev
      - libxml2-runtime
  - name: libxml2-tools
    files:
      include:
        - Library/bin/*.exe
    requirements:
      - libxml2-runtime

about:
  home: http://xmlsoft.org/
  license: MIT
  license_family: MIT
  license_file: Copyright
  summary: The XML C parser and toolkit of Gnome
  description: |
    Though libxml2 is written in C a variety of language
    bindings make it available in other environments.
  doc_url: http://xmlsoft.org/html/index.html
  doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/devhelp/index.html
  dev_url: https://git.gnome.org/browse/libxml2/
