{% set version = "3.6.0" %}

package:
  name: openssl
  version: {{ version }}

source:
  url: https://github.com/openssl/openssl/releases/download/openssl-{{ version }}/openssl-{{ version }}.tar.gz
  sha256: b6a5f44b7eb69e3fa35dbf15524405b44837a481d43d81daddde3ff21fcbb8e9
  patches:
    - lib.patch
    - reloc.patch

requirements:
  build:
    - {{ compiler('c') }}
    - nasm
    - perl
    - m2-patch
  host:
    - zlib
    - brotli-full
    - zstd-dev
    - prefix-stub-dev
  run:
    - openssl-runtime
    - openssl-dev
    - openssl-tools

outputs:
  - name: openssl-runtime
    files:
      include:
        - Library/bin/*.dll
        - Library/SSL
        - Library/lib/engines-3
        - Library/lib/ossl-modules
    requirements:
      - brotli-runtime
      - prefix-stub-runtime
      - zlib-runtime
      - zstd-runtime
  - name: openssl-dev
    files:
      include:
        - Library/lib
        - Library/include
        - Library/html
    run_exports:
      - openssl-runtime
    requirements:
      run:
        - brotli-dev
        - openssl-runtime
        - zlib-dev
        - zstd-dev
  - name: openssl-tools
    files:
      include:
        - Library/bin/*.exe
        - Library/bin/*.pl
    requirements:
      - openssl-runtime
