{% set version = "0.0.0" %}

package:
  name: prefix-stub-split
  version: {{ version }}

source:
  url: https://github.com/paperchalice/prefix-stub/archive/refs/heads/main.zip

requirements:
  build:
    - {{ compiler("c") }}
    - cmake-no-system
    

outputs:
  - name: prefix-stub-runtime
    files:
      - Library/bin/*.dll
  - name: prefix-stub-dev
    build:
      run_exports:
        - {{ pin_subpackage("prefix-stub-runtime", max_pin="x") }}
    files:
      - Library/include
      - Library/lib
  - name: prefix-stub
    requirements:
      run:
        - prefix-stub-runtime
        - prefix-stub-dev
