{% set name = "pcre2-split" %}
{% set version = "10.45" %}

package:
  name: {{ name }}
  version: head

source:
  - url: https://github.com/PCRE2Project/pcre2/archive/refs/tags/pcre2-{{ version }}.tar.gz
    sha256: 35ce7d21f511c4a81d7079164077d25fbc41af00f19e1b547801df905c5f0fab
  - url: https://github.com/zherczeg/sljit/archive/e51eabbfb8eabc6526f56e4e88b29fb10d1ee048.tar.gz
    sha256: 5caf31959f4c2dfa9fdbaf290b0e16538527d929d5c1c5bd1a3e6df01436c1cf
    folder: deps/sljit

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - bzip2-dev
    - zlib-dev

outputs:
  - name: pcre2-runtime
    files:
      - Library/bin/*.dll
    requirements:
      - bzip2-runtime
      - zlib-runtime
  - name: pcre2-dev
    files:
      - Library/include
      - Library/lib
      - Library/share
    build:
      run_exports:
        # https://abi-laboratory.pro/index.php?view=timeline&l=pcre2
        - {{ pin_subpackage("pcre2-runtime", max_pin="x.x") }}
    requirements:
      host:
        - bzip2-dev
        - zlib-dev
  - name: pcre2-tools
    files:
      - Library/bin/*.exe
    requirements:
      - pcre2-runtime

about:
  home: http://www.pcre.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Regular expression pattern matching using Perl 5 syntax and semantics.
  description: |
    The PCRE library is a set of functions that implement regular expression pattern matching
    using the same syntax and semantics as Perl 5. PCRE has its own native API, as well as a set of
    wrapper functions that correspond to the POSIX regular expression API. The PCRE library is
    free, even for building proprietary software.
  doc_url: http://www.pcre.org/current/doc/html/
