recipe:
  name: vc
  version: "14.99.0"

outputs:
  - package:
      name: vs
      version: 18
    requirements:
      run:
        - jom
        - ninja
        - vswhere
    build:
      script:
        interpreter: powershell
        content: |
          New-Item -ItemType Directory -Force $PREFIX/etc/conda/activate.d
          Copy-Item -Path $RECIPE_DIR/vs_activate.ps1 -Destination $PREFIX/etc/conda/activate.d
  - package:
      name: ucrt
  - package:
      name: vc
  - package:
      name: vc14_runtime
  - package:
      name: vcomp14
