{% set version = "2.10" %}
{% set version_major = "2" %}

package:
  name: lzo
  version: {{ version }}

source:
  url: http://www.oberhumer.com/opensource/lzo/download/lzo-{{ version }}.tar.gz
  sha256: c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - m2-pkg-config

outputs:
  - name: lzo-runtime
    files:
      - Library/bin/*.dll
  - name: lzo-dev
    files:
      - Library/include
      - Library/lib
    build:
      run_exports:
        strong:
          - lzo-runtime
  - name: lzo-full
    requirements:
      run:
        - lzo-dev
        - lzo-runtime

about:
  home: http://www.oberhumer.com/opensource/lzo/
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: COPYING
  summary: LZO is a portable lossless data compression library written in ANSI C.
  description: |
    LZO offers pretty fast compression and extremely fast decompression.
    MiniLZO is a very lightweight subset of the LZO library.
