{% set version = "2.2.4" %}

package:
  name: zlib
  version: {{ version }}

source:
  url: https://github.com/zlib-ng/zlib-ng/archive/refs/tags/{{ version }}.tar.gz
  sha256: a73343c3093e5cdc50d9377997c3815b878fd110bf6511c2c7759f2afb90f5a3
  fn: zlib-ng.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake

outputs:
  - name: zlib-dev
    files:
      - Library/include
      - Library/lib
  - name: zlib-runtime
    files:
      - Library/bin/*.dll
  - name: zlib-tool
    requirements:
      run:
        - zlib-runtime
    files:
      - Library/bin/*.exe

test:
  commands:
    - echo "this is zlib-ng"

about:
  home: https://github.com/zlib-ng/zlib-ng
  license: Zlib
  license_family: Other
  license_file: LICENSE.md
  summary: zlib data compression library for the next generation systems
