{% set version = "2.2.4" %}

package:
  name: zlib
  version: {{ version }}

source:
  url: https://github.com/zlib-ng/zlib-ng/archive/refs/tags/{{ version }}.tar.gz
  sha256: a73343c3093e5cdc50d9377997c3815b878fd110bf6511c2c7759f2afb90f5a3
  fn: zlib-ng.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake

test:
  commands:
    - if not exist %LIBRARY_INC%\zlib-ng.h exit 1               # [win]
    - if not exist %LIBRARY_INC%\zconf-ng.h exit 1              # [win]
    - if not exist %LIBRARY_BIN%\zlib-ng2.dll exit 1            # [win]
    - if not exist %LIBRARY_LIB%\zlib-ng.lib exit 1.            # [win]
    - if not exist %LIBRARY_LIB%\pkgconfig\zlib-ng.pc exit 1    # [win]

about:
  home: https://github.com/zlib-ng/zlib-ng
  license: Zlib
  license_family: Other
  license_file: LICENSE.md
  summary: zlib data compression library for the next generation systems
