{% set version = "2.2.5" %}

package:
  name: zlib
  version: {{ version }}

source:
  url: https://github.com/zlib-ng/zlib-ng/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5b3b022489f3ced82384f06db1e13ba148cbce38c7941e424d6cb414416acd18
  fn: zlib-ng.tar.gz
  patches:
    - archive_name.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - m2-patch
  run:
    - zlib-runtime
    - zlib-dev
    - zlib-tools

outputs:
  - name: zlib-runtime
    files:
      - Library/bin/*.dll
  - name: zlib-dev
    files:
      - Library/include
      - Library/lib
    build:
      run_exports:
          - zlib-runtime
  - name: zlib-tools
    requirements:
      run:
        - zlib-runtime
    files:
      - Library/bin/*.exe

test:
  commands:
    - echo "this is zlib-ng"

about:
  home: https://github.com/zlib-ng/zlib-ng
  license: Zlib
  license_family: Other
  license_file: LICENSE.md
  summary: zlib data compression library for the next generation systems
