{% set version = "0.25" %}

package:
  name: gettext-static
  version: {{ version }}

source:
  url: https://mirrors.tuna.tsinghua.edu.cn/gnu/gettext/gettext-{{ version }}.tar.xz
  sha256: 05240b29f5b0f422e5a4ef8e9b5f76d8fa059cc057693d2723cdb76f36a88ab0

requirements:
  build:
    - {{ compiler('c') }}
    - libiconv-dev
    - m2-aux
    - m2-autoconf
    - m2-automake-wrapper
    - m2-bash
    - m2-findutils
    - m2-grep
    - m2-libtool
    - m2-m4
    - m2-make
    - m2-patch
