{% set version = "0.25" %}

package:
  name: gettext-static
  version: {{ version }}

source:
  url: https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.25-v1.17/gettext0.25-iconv1.17-static-64.zip

requirements:
  build:
    - {{ compiler('c') }}
