{% set version = "3.8.1" %}

package:
  name: libarchive-split
  version: {{ version }}

source:
  url: https://github.com/libarchive/libarchive/archive/v{{ version }}.tar.gz
  sha256: ad5dfe0d9a5999494c445b9bc3271d84160950bb1790cf892fb132f563d036b6

requirements:
  build:
    - {{ compiler('c') }}
    - bzip2-dev
    - libb2-dev
    - libiconv-dev
    - liblzma-dev
    - lz4-dev
    - lzo-dev
    - openssl-dev
    - pcre2-dev
    - pkgconf-tools
    - zlib-dev
    - zstd-dev

outputs:
  - name: libarchive-runtime
    files:
      - Library/bin/*.dll
    requirements:
      - bzip2-runtime
      - libb2-runtime
      - libiconv-runtime
      - liblzma-runtime
      - lz4-runtime
      - lzo-runtime
      - openssl-runtime
      - pcre2-runtime
      - zlib-runtime
      - zstd-runtime
  - name: libarchive-dev
    files:
      - Library/include
      - Library/lib
      - Library/share
    build:
      run_exports:
        - libarchive-runtime
  - name: libarchive-tools
    files:
      - Library/bin/*.exe
    requirements:
      - libarchive-runtime
