context:
  version: "1.6.58"

recipe:
  name: libpng
  version: ${{ version }}

source:
  url: https://github.com/pnggroup/libpng/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a9d4df463d36a6e5f9c29bd6f4967312d17e996c1854f3511f833924eb1993cf
  patches:
    - name.patch

outputs:
  - staging:
      name: libpng-split
    requirements:
      build:
        - vs
        - cmake
        - zlib-full

  - package:
      name: libpng-runtime
    inherit:
      from: libpng-split
    build:
      files:
        - Library/bin/*.dll
    requirements:
      run:
        - zlib-runtime
  - package:
      name: libpng-dev
    inherit:
      from: libpng-split
    build:
      files:
        - Library/include
        - Library/lib
        - Library/share
    requirements:
      run:
        - libpng-runtime
      run_exports:
        - libpng-runtime
  - package:
      name: libpng-tools
    inherit:
      from: libpng-split
    build:
      files:
        - Library/bin/*.exe
    requirements:
      run:
        - libpng-runtime
    
  - package:
      name: libpng-full
    requirements:
      run:
        - libpng-dev
        - libpng-runtime
        - libpng-tools

about:
  license: zlib-acknowledgement
  license_file: LICENSE
  summary: PNG reference library
  description: |
    libpng is the official PNG reference library. It supports almost all PNG
    features, is extensible, and has been extensively tested for over 20 years.
  homepage: http://www.libpng.org/pub/png/libpng.html
  repository: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
  documentation: http://www.libpng.org/pub/png/libpng.html

