context:
  version: "0.12.2"

recipe:
  name: libssh-split
  version: ${{ version }}

source:
  url: https://www.libssh.org/files/${{ (version|split("."))[0:2]|join(".") }}/libssh-${{ version }}.tar.xz
  sha256: 49560f677d96e3706a904ac2de1116e25f3680937d51e5c92198fcba4a1c1e9f

outputs:
  - staging:
      name: libssh-split
    requirements:
      build:
        - vs
        - cmake-no-system
        - krb5-tools
      host:
        - krb5-dev
        - openssl-dev
        - zlib-dev

  - package:
      name: libssh-runtime
    inherit:
      from: libssh-split
      run_exports: false
    build:
      files:
        include:
          - Library/bin/*.dll
    requirements:
      run:
        - krb5-runtime
        - openssl-runtime
        - zlib-runtime
  - package:
      name: libssh-dev
    inherit: libssh-split
    build:
      files:
        include:
          - Library/include
          - Library/lib
    requirements:
      run:
        - libssh-runtime
      run_exports:
        - libssh-runtime
