context:
  version: "8.19.0"

recipe:
  name: curl-split
  version: ${{ version }}

source:
  url: http://curl.haxx.se/download/curl-${{ version }}.tar.xz
  sha256: 4eb41489790d19e190d7ac7e18e82857cdd68af8f4e66b292ced562d333f11df
  patches:
    - cert.patch

outputs:
  - staging:
      name: curl-split
    requirements:
      build:
        - vs
        - if: win
          then: cmake-no-system
        - pkgconf-tools
      host:
        - c-ares-dev
        - brotli-dev
        - libpsl-dev
        - nghttp3-dev
        - nghttp2-dev
        - ngtcp2-dev
        - zlib-dev
        - zstd-dev
        - libssh-dev
        - openssl-dev
        - prefix-stub-runtime
        - prefix-stub-dev
        - rtmpdump-dev
      ignore_run_exports:
        from_package:
          - prefix-stub-dev
    build:
      script: bld.ps1

  - package:
      name: curl-runtime
    inherit: curl-split
    build:
      files:
        include:
          - Library/bin/*.dll
  - package:
      name: curl-dev
    inherit: curl-split
    build:
      files:
        include:
          - Library/include
          - Library/lib
          - Library/share
    requirements:
      run_exports:
        - curl-runtime
  - package:
      name: curl-tools
    inherit: curl-split
    build:
      files:
        include:
          - Library/bin/*.exe
          - Library/bin/curl-config
    requirements:
      run:
        - curl-runtime
        - prefix-stub-runtime
  
  - package:
      name: curl-full
    requirements:
      run:
        - curl-dev
        - curl-tools

about:
  license: curl
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax
  description: |
    Curl is an open source command line tool and library for transferring data
    with URL syntax. It is used in command lines or scripts to transfer data.
  homepage: http://curl.haxx.se/
  repository: https://github.com/curl/curl
  documentation: https://curl.haxx.se/docs/
