context:
  name: zlib
  version: "2.3.3"

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/zlib-ng/zlib-ng/archive/refs/tags/${{ version }}.tar.gz
  sha256: f9c65aa9c852eb8255b636fd9f07ce1c406f061ec19a2e7d508b318ca0c907d1
  patches:
    - archive_name.patch

outputs:
  - staging:
      name: zlib-split
    requirements:
      build:
        - cmake-no-system
        - vs
    build:
      script: bld.ps1

  - package:
      name: zlib-dev
    inherit:
      from: zlib-split
    build:
      files:
        - Library/lib
        - Library/include
    requirements:
      run_exports:
          - zlib-runtime
      run:
        - zlib-runtime
  - package:
      name: zlib-runtime
    inherit:
      from: zlib-split
    build:
      files:
        - Library/bin/*.dll
  - package:
      name: zlib-tools
    inherit:
      from: zlib-split
    requirements:
      run:
        - zlib-runtime
    build:
      files:
        - Library/bin/*.exe
  - package:
      name: zlib-full
    requirements:
      run:
        - zlib-dev
        - zlib-runtime
        - zlib-tools

about:
  homepage: https://github.com/zlib-ng/zlib-ng
  license: Zlib
  summary: zlib data compression library for the next generation systems
