context:
  name: zlib
  version: "2.3.3"

recipe:
  name: ${{ name }}
  version: ${{ version }}

cache:
  source:
    url: https://github.com/zlib-ng/zlib-ng/archive/refs/tags/${{ version }}.tar.gz
    sha256: f9c65aa9c852eb8255b636fd9f07ce1c406f061ec19a2e7d508b318ca0c907d1
    patches:
      - archive_name.patch
  requirements:
    build:
      - cmake-no-system
      - visual-studio
  build:
    script: bld.ps1

outputs:
  - package:
      name: zlib-dev
    build:
      files:
        - Library/lib
        - Library/include
    requirements:
      run_exports:
          - zlib-runtime
      run:
        - zlib-runtime
  - package:
      name: zlib-runtime
    build:
      files:
        - Library/bin/*.dll
  - package:
      name: zlib-tools
    requirements:
      run:
        - zlib-runtime
    build:
      files:
        - Library/bin/*.exe
